### ISSUE TITLE
Todo ver1.9

### ISSUE THREAD

**Issue by MinecrafterJPN** [MinecrafterJPN/ChestShop#5]
- [x] Use of metadata
- [x] Improve database
- [x] command like ID searcher
- [x] Make new tutorial video
